2021-12-14 15:05:38,655 INFO    MainThread:14617 [wandb_setup.py:_flush():71] setting env: {}
2021-12-14 15:05:38,655 INFO    MainThread:14617 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-14 15:05:38,655 INFO    MainThread:14617 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-14 15:05:38,655 INFO    MainThread:14617 [wandb_init.py:_log_setup():371] Logging user logs to /home/matteo/NeuroGEN/TorVergataExperiments/Generative/wandb/run-20211214_150538-ogiqjm3k/logs/debug.log
2021-12-14 15:05:38,655 INFO    MainThread:14617 [wandb_init.py:_log_setup():372] Logging internal logs to /home/matteo/NeuroGEN/TorVergataExperiments/Generative/wandb/run-20211214_150538-ogiqjm3k/logs/debug-internal.log
2021-12-14 15:05:38,655 INFO    MainThread:14617 [wandb_init.py:init():404] calling init triggers
2021-12-14 15:05:38,655 INFO    MainThread:14617 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {'dataset': 'celebA', 'type': 'PG-GAN', 'nota': 'DGX'}
2021-12-14 15:05:38,655 INFO    MainThread:14617 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 23od6noo
2021-12-14 15:05:38,656 INFO    MainThread:14617 [wandb_run.py:finish():1463] finishing run matteoferrante/TorVergataExperiment-Generative/23od6noo
2021-12-14 15:05:38,670 INFO    MainThread:14617 [jupyter.py:save_history():458] saving 12 cells to _session_history.ipynb
2021-12-14 15:05:38,689 INFO    MainThread:14617 [wandb_run.py:_config_callback():962] config_cb ('_wandb', 'session_history') code/_session_history.ipynb None
2021-12-14 15:05:38,729 INFO    MainThread:14617 [jupyter.py:save_ipynb():377] looking for notebook: None
2021-12-14 15:05:38,729 INFO    MainThread:14617 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2021-12-14 15:05:38,729 INFO    MainThread:14617 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 0
2021-12-14 15:05:38,729 INFO    MainThread:14617 [wandb_run.py:_restore():1758] restore
2021-12-14 15:05:39,504 INFO    MainThread:14617 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 2
}
pusher_stats {
  uploaded_bytes: 732585
  total_bytes: 732585
}

2021-12-14 15:05:39,613 INFO    MainThread:14617 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 2
}
pusher_stats {
  uploaded_bytes: 732585
  total_bytes: 732585
}

2021-12-14 15:05:39,802 INFO    MainThread:14617 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 2
}
pusher_stats {
  uploaded_bytes: 732585
  total_bytes: 732585
}

2021-12-14 15:05:39,945 INFO    MainThread:14617 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 732585
  total_bytes: 737098
}

2021-12-14 15:05:40,046 INFO    MainThread:14617 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 732585
  total_bytes: 744170
}

2021-12-14 15:05:40,148 INFO    MainThread:14617 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 732585
  total_bytes: 744170
}

2021-12-14 15:05:40,249 INFO    MainThread:14617 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 744170
  total_bytes: 744170
}

2021-12-14 15:05:40,350 INFO    MainThread:14617 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 744170
  total_bytes: 744170
}

2021-12-14 15:05:40,452 INFO    MainThread:14617 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 744170
  total_bytes: 744170
}

2021-12-14 15:05:40,553 INFO    MainThread:14617 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 744170
  total_bytes: 744170
}

2021-12-14 15:05:40,654 INFO    MainThread:14617 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 744170
  total_bytes: 744170
}

2021-12-14 15:05:40,956 INFO    MainThread:14617 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 744170
  total_bytes: 744170
}

2021-12-14 15:05:41,386 INFO    MainThread:14617 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 744170
  total_bytes: 744170
}
local_info {
}

2021-12-14 15:05:42,767 INFO    MainThread:14617 [wandb_run.py:_append_files():2184] logging synced files
2021-12-14 15:05:42,770 INFO    MainThread:14617 [wandb_init.py:init():449] starting backend
2021-12-14 15:05:42,771 INFO    MainThread:14617 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-12-14 15:05:42,773 INFO    MainThread:14617 [backend.py:ensure_launched():199] starting backend process...
2021-12-14 15:05:42,781 INFO    MainThread:14617 [backend.py:ensure_launched():204] started backend process with pid: 15717
2021-12-14 15:05:42,782 INFO    MainThread:14617 [wandb_init.py:init():458] backend started and connected
2021-12-14 15:05:42,784 INFO    MainThread:14617 [wandb_run.py:_label_probe_notebook():917] probe notebook
2021-12-14 15:05:42,784 INFO    MainThread:14617 [wandb_run.py:_label_probe_notebook():927] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-12-14 15:05:42,784 INFO    MainThread:14617 [wandb_init.py:init():519] updated telemetry
2021-12-14 15:05:42,800 INFO    MainThread:14617 [wandb_init.py:init():549] communicating current version
2021-12-14 15:05:43,499 INFO    MainThread:14617 [wandb_init.py:init():554] got version response 
2021-12-14 15:05:43,499 INFO    MainThread:14617 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-12-14 15:05:43,702 INFO    MainThread:14617 [wandb_init.py:init():592] starting run threads in backend
2021-12-14 15:05:44,483 WARNING MainThread:14617 [wandb_init.py:init():938] interrupted
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_init.py", line 917, in init
    run = wi.init()
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_init.py", line 597, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/interface/interface.py", line 216, in communicate_run_start
    result = self._communicate_run_start(run_start)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/interface/interface_queue.py", line 446, in _communicate_run_start
    result = self._communicate(rec)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/interface/interface_queue.py", line 232, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/interface/router.py", line 32, in get
    is_set = self._object_ready.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
